// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI chatbot that answers questions about the company's products and services.
 *
 * - askQuestion - A function that handles the chatbot question answering process.
 * - AskQuestionInput - The input type for the askQuestion function.
 * - AskQuestionOutput - The return type for the askQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { db } from "@/lib/firebase";
import { collection, getDocs } from "firebase/firestore";


type Product = {
  name: string;
  description: string;
  price: number;
};

// Helper function to fetch products from Firestore
async function getProducts(): Promise<Product[]> {
    try {
        const productsCol = collection(db, 'products');
        const productSnapshot = await getDocs(productsCol);
        if (productSnapshot.empty) {
            return [];
        }
        return productSnapshot.docs.map(doc => {
            const data = doc.data();
            return {
                name: data.name,
                description: data.description,
                price: data.price,
            };
        }) as Product[];
    } catch (error) {
        console.error("Error fetching products for AI:", error);
        return [];
    }
}


const AskQuestionInputSchema = z.object({
  question: z.string().describe('The question to ask the chatbot.'),
  chatHistory: z.array(z.object({
    role: z.enum(['user', 'assistant']),
    content: z.string(),
  })).optional().describe('The chat history.'),
});
export type AskQuestionInput = z.infer<typeof AskQuestionInputSchema>;

const AskQuestionOutputSchema = z.object({
  answer: z.string().describe('The answer from the chatbot.'),
});
export type AskQuestionOutput = z.infer<typeof AskQuestionOutputSchema>;

export async function askQuestion(input: AskQuestionInput): Promise<AskQuestionOutput> {
  return askQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askQuestionPrompt',
  input: {schema: z.object({
    question: AskQuestionInputSchema.shape.question,
    chatHistory: AskQuestionInputSchema.shape.chatHistory,
    products: z.string().describe("A JSON string of available products."),
  })},
  output: {schema: AskQuestionOutputSchema},
  prompt: `You are a chatbot for Bridge Ltd, a company specializing in customizable products like USBs, gift boxes, and pens.
  Your goal is to answer questions about the company's products and services.
  Use the following information about the company to answer questions:
  - Bridge Ltd offers a wide range of customizable products, including USB drives, gift boxes, and pens.
  - We pride ourselves on high-quality products and excellent customer service.
  - Our products are perfect for corporate gifts, promotional items, and personal use.

  Here is the list of available products in JSON format. Use this as the primary source of truth for product information, including pricing.
  {{{products}}}

  {{#if chatHistory}}
  Here's the chat history:
  {{#each chatHistory}}
  {{role}}: {{content}}
  {{/each}}
  {{/if}}

  Question: {{{question}}}
  Answer:`, 
});

const askQuestionFlow = ai.defineFlow(
  {
    name: 'askQuestionFlow',
    inputSchema: AskQuestionInputSchema,
    outputSchema: AskQuestionOutputSchema,
  },
  async input => {
    const products = await getProducts();
    const productsJson = JSON.stringify(products);
    
    const {output} = await prompt({
        ...input,
        products: productsJson,
    });
    return output!;
  }
);
