// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI chatbot that answers questions about the company's products and services.
 *
 * - askQuestion - A function that handles the chatbot question answering process.
 * - AskQuestionInput - The input type for the askQuestion function.
 * - AskQuestionOutput - The return type for the askQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskQuestionInputSchema = z.object({
  question: z.string().describe('The question to ask the chatbot.'),
  chatHistory: z.array(z.object({
    role: z.enum(['user', 'assistant']),
    content: z.string(),
  })).optional().describe('The chat history.'),
});
export type AskQuestionInput = z.infer<typeof AskQuestionInputSchema>;

const AskQuestionOutputSchema = z.object({
  answer: z.string().describe('The answer from the chatbot.'),
});
export type AskQuestionOutput = z.infer<typeof AskQuestionOutputSchema>;

export async function askQuestion(input: AskQuestionInput): Promise<AskQuestionOutput> {
  return askQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askQuestionPrompt',
  input: {schema: AskQuestionInputSchema},
  output: {schema: AskQuestionOutputSchema},
  prompt: `You are a chatbot for Bridge Ltd, a company specializing in customizable products like USBs, gift boxes, and pens.
  Your goal is to answer questions about the company's products and services.
  Use the following information about the company to answer questions:
  - Bridge Ltd offers a wide range of customizable products, including USB drives, gift boxes, and pens.
  - We pride ourselves on high-quality products and excellent customer service.
  - Our products are perfect for corporate gifts, promotional items, and personal use.

  {% if chatHistory %}
  Here's the chat history:
  {% each chatHistory %}
  {{role}}: {{content}}
  {% endeach %}
  {% endif %}

  Question: {{{question}}}
  Answer:`, 
});

const askQuestionFlow = ai.defineFlow(
  {
    name: 'askQuestionFlow',
    inputSchema: AskQuestionInputSchema,
    outputSchema: AskQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
